#pragma once

#define HW_IOREG                0x04000000
#define HW_REG_BASE             HW_IOREG  // alias

#define REG_DISPCNT_OFFSET 0x0
#define REG_DISPCNT_ADDR (HW_REG_BASE + REG_DISPCNT_OFFSET)
#define reg_GX_DISPCNT (*(REGType32v *)REG_DISPCNT_ADDR)  // =0x4000000

#define REG_DB_DISPCNT_OFFSET 0x1000
#define REG_DB_DISPCNT_ADDR (HW_REG_BASE + REG_DB_DISPCNT_OFFSET)
#define reg_GXS_DB_DISPCNT (*(REGType32v *)REG_DB_DISPCNT_ADDR)  // =0x4001000